linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - revive
    - misspell
    - prealloc
    - gosec
    - bodyclose
    - sqlclosecheck

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  gosec:
    severity: medium
    confidence: medium

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default-severity: warning
  rules:
    - linters:
        - gosec
      severity: error
